// Alle Texte der Website in drei Sprachen. Deutsch ist die Vorlage – die
// Typen leiten sich daraus ab, damit in EN und ES kein Schluessel fehlt.
// Impressum und Datenschutz bleiben deutsch (Rechtstexte).

export type Sprache = "de" | "en" | "es";

const DE = {
  nav: { leistungen: "Leistungen", ueberMich: "Über mich", projekte: "Projekte", kontakt: "Kontakt", anfragen: "Projekt anfragen" },
  leistungen: {
    titel: "Leistungen",
    eintraege: [
      {
        eyebrow: "Smart Websites",
        titel: "Eine Website, die arbeitet.",
        text: "Schnell, mobil, für Google gebaut – mit Anfragen, Terminen und Buchungen direkt auf der Seite.",
        punkte: ["Anfragen & Termine", "Online-Buchung", "Lädt in unter einer Sekunde"],
        alt: ["Startseite der Autohaus-Demo", "Dieselbe Seite auf dem Handy"],
      },
      {
        eyebrow: "Verwaltungsbereich",
        titel: "Alles an einer Stelle.",
        text: "Anfragen, Belegungen, Bestand, Besucherzahlen – Sie ändern selbst, ohne Agentur.",
        punkte: ["Anfragen & Termine", "Belegungsplan & Bestand", "Besucherzahlen"],
        alt: ["Übersicht im Verwaltungsbereich der Autohaus-Demo", "Belegungsplan für Mietwagen"],
      },
      {
        eyebrow: "KI als Beschleuniger",
        titel: "Gute Idee heute. Online morgen.",
        text: "KI ersetzt keine Idee – sie macht die Umsetzung schnell. Beispiel Instagram: Foto wählen, Text kommt von der KI, Beitrag einplanen. Fertig.",
        punkte: ["Instagram-Beiträge in Minuten", "Änderungen an der Website in Tagen", "Texte und Bilder in Ihrem Ton"],
        alt: ["Instagram-Beitrag im Verwaltungsbereich erstellen", ""],
      },
    ],
  },
  geo: {
    eyebrow: "GEO – Generative Engine Optimization",
    titel: "Auch von ChatGPT & Google AI empfohlen.",
    text: "Kunden fragen heute eine KI. Genannt wird, wer klare Fakten liefert – dafür richte ich Website und Google-Profil ein.",
    punkte: ["Strukturierte Daten", "Fragen & Antworten", "Google-Unternehmensprofil"],
    kopf: "KI-Antwort",
    frage: "Welche Werkstatt in Würzburg macht samstags Reifenwechsel?",
    antwortName: "Autohaus Mustermann",
    antwort: " in Würzburg bietet samstags von 9 bis 13 Uhr Reifenwechsel an, Termine lassen sich online buchen. Kunden bewerten den Betrieb mit 4,8 von 5 Sternen.",
    quellen: ["autohaus-mustermann.de", "Google Unternehmensprofil", "Bewertungen · 4,8 ★"],
    aria: "Beispiel: KI-Antwort, die den Betrieb empfiehlt",
  },
  ueber: {
    eyebrow: "Über mich",
    titel1: "Ihr Ansprechpartner",
    titel2: "aus Würzburg",
    text: "Ich bin Ihsan, Wirtschaftsinformatiker aus Würzburg. Ich baue Websites für lokale Betriebe – mit Funktionen, die früher nur große Firmen hatten.",
    linkedin: "Auf LinkedIn vernetzen",
    linkedinAria: "LinkedIn-Profil von Ihsan Yilmaz",
    werte: ["Keine langen Vertragslaufzeiten", "Änderungen und Updates unkompliziert möglich"],
    vorteile: [
      { titel: "Persönlich & unkompliziert", text: "Eine Ansprechperson, keine Warteschleife." },
      { titel: "Schnelle Umsetzung", text: "In der Regel wenige Wochen bis online." },
      { titel: "Faire Preise", text: "Festpreis vorab, keine versteckten Kosten." },
    ],
  },
  instagram: { unter: "Websites für lokale Betriebe", folgen: "@aiy.web folgen", ansehen: "Beitrag auf Instagram ansehen" },
  projekte: {
    titel: "Projekte",
    anfragen: "Ihr Projekt anfragen",
    status: { online: "Online", inArbeit: "In Arbeit" },
    tags: { web: "Webentwicklung", automatisierung: "Automatisierung" },
    eintraege: [
      { titel: "Autohaus-Website", text: "Fahrzeuge, Anfragen und Werkstatt-Termine auf einer Seite.", tech: ["Next.js", "Cloudflare Pages", "Kontaktformular", "Webshop-Anbindung"] },
      { titel: "Gastronomie-Website", text: "Speisekarte, Öffnungszeiten und Kontakt — klar aufgebaut.", tech: ["Next.js", "Tailwind CSS", "Cloudflare Pages", "Smarte Speisekarte"] },
      { titel: "Instagram-Automatisierung", text: "Beiträge im Browser bauen, einplanen — und zur gewählten Zeit geht alles von selbst raus.", tech: ["Cloudflare Worker", "Instagram-API", "Bildbearbeitung", "Zeitplanung"] },
      { titel: "Mietwagen-Buchungstool", text: "Fahrzeug wählen, Zeitraum festlegen, anfragen — Verfügbarkeit live.", tech: ["Next.js", "Buchungskalender", "Verfügbarkeiten", "Online-Anfrage"] },
    ],
  },
  kontakt: {
    eyebrow: "Kontakt",
    titel1: "Lassen Sie uns",
    titel2: "zusammenarbeiten",
    text: "Schreiben Sie mir, worum es geht — ich melde mich innerhalb von 24 Stunden.",
    email: "E-Mail",
    karte: "Standort – Oberer Mainkai 9, 97070 Würzburg (OpenStreetMap)",
    maps: "In Google Maps öffnen",
    gesendet: "Nachricht gesendet!",
    gesendetText: "Ich melde mich so schnell wie möglich bei Ihnen.",
    nochmal: "Weitere Nachricht senden",
    name: "Name *", namePlatz: "Max Mustermann",
    betrieb: "Betrieb / Lokal", betriebPlatz: "Zum goldenen Löwen",
    emailFeld: "E-Mail *", emailPlatz: "max@muster.de",
    anliegen: "Ihr Anliegen *", anliegenPlatz: "Kurze Beschreibung Ihres Projekts...",
    fehler: "Etwas ist schiefgelaufen. Bitte versuchen Sie es erneut.",
    senden: "Nachricht senden", sendet: "Wird gesendet...",
    zustimmung1: "Mit dem Absenden stimmen Sie der Verarbeitung Ihrer Angaben gemäß ",
    datenschutz: "Datenschutzerklärung",
    zustimmung2: " zu. Ich antworte innerhalb von 24 Stunden.",
  },
  fuss: {
    text: "Websites für lokale Betriebe und kleine Unternehmen.",
    impressum: "Impressum", datenschutz: "Datenschutz",
    rechte: "Alle Rechte vorbehalten.",
  },
};

export type Texte = typeof DE;

const EN: Texte = {
  nav: { leistungen: "Services", ueberMich: "About", projekte: "Projects", kontakt: "Contact", anfragen: "Request a project" },
  leistungen: {
    titel: "Services",
    eintraege: [
      {
        eyebrow: "Smart Websites",
        titel: "A website that works for you.",
        text: "Fast, mobile, built for Google – with enquiries, appointments and bookings right on the page.",
        punkte: ["Enquiries & appointments", "Online booking", "Loads in under a second"],
        alt: ["Home page of the car dealer demo", "The same page on a phone"],
      },
      {
        eyebrow: "Admin area",
        titel: "Everything in one place.",
        text: "Enquiries, bookings, stock, visitor numbers – you make changes yourself, no agency needed.",
        punkte: ["Enquiries & appointments", "Booking calendar & stock", "Visitor numbers"],
        alt: ["Overview in the demo admin area", "Booking calendar for rental cars"],
      },
      {
        eyebrow: "AI as an accelerator",
        titel: "Good idea today. Online tomorrow.",
        text: "AI doesn't replace an idea – it makes execution fast. Take Instagram: pick a photo, the AI writes the text, schedule the post. Done.",
        punkte: ["Instagram posts in minutes", "Website changes in days", "Text and images in your tone"],
        alt: ["Creating an Instagram post in the admin area", ""],
      },
    ],
  },
  geo: {
    eyebrow: "GEO – Generative Engine Optimization",
    titel: "Recommended by ChatGPT & Google AI, too.",
    text: "Customers ask an AI these days. It names whoever provides clear facts – that's what I set up your website and Google profile for.",
    punkte: ["Structured data", "Questions & answers", "Google Business Profile"],
    kopf: "AI answer",
    frage: "Which garage in Würzburg changes tyres on Saturdays?",
    antwortName: "Autohaus Mustermann",
    antwort: " in Würzburg changes tyres on Saturdays from 9 am to 1 pm, and appointments can be booked online. Customers rate the business 4.8 out of 5 stars.",
    quellen: ["autohaus-mustermann.de", "Google Business Profile", "Reviews · 4.8 ★"],
    aria: "Example: an AI answer recommending the business",
  },
  ueber: {
    eyebrow: "About me",
    titel1: "Your contact",
    titel2: "in Würzburg",
    text: "I'm Ihsan, a business IT specialist from Würzburg. I build websites for local businesses – with features that used to be reserved for big companies.",
    linkedin: "Connect on LinkedIn",
    linkedinAria: "LinkedIn profile of Ihsan Yilmaz",
    werte: ["No long contract terms", "Changes and updates made easy"],
    vorteile: [
      { titel: "Personal & straightforward", text: "One contact person, no hotline." },
      { titel: "Fast delivery", text: "Usually a few weeks until you're online." },
      { titel: "Fair prices", text: "Fixed price up front, no hidden costs." },
    ],
  },
  instagram: { unter: "Websites for local businesses", folgen: "Follow @aiy.web", ansehen: "View post on Instagram" },
  projekte: {
    titel: "Projects",
    anfragen: "Request your project",
    status: { online: "Live", inArbeit: "In progress" },
    tags: { web: "Web development", automatisierung: "Automation" },
    eintraege: [
      { titel: "Car dealer website", text: "Vehicles, enquiries and workshop appointments on one site.", tech: ["Next.js", "Cloudflare Pages", "Contact form", "Shop integration"] },
      { titel: "Restaurant website", text: "Menu, opening hours and contact — clearly laid out.", tech: ["Next.js", "Tailwind CSS", "Cloudflare Pages", "Smart menu"] },
      { titel: "Instagram automation", text: "Build posts in the browser, schedule them — and at the chosen time everything goes out by itself.", tech: ["Cloudflare Worker", "Instagram API", "Image editing", "Scheduling"] },
      { titel: "Rental car booking tool", text: "Choose a vehicle, set the dates, send a request — availability live.", tech: ["Next.js", "Booking calendar", "Availability", "Online request"] },
    ],
  },
  kontakt: {
    eyebrow: "Contact",
    titel1: "Let's work",
    titel2: "together",
    text: "Tell me what it's about — I'll get back to you within 24 hours.",
    email: "Email",
    karte: "Location – Oberer Mainkai 9, 97070 Würzburg (OpenStreetMap)",
    maps: "Open in Google Maps",
    gesendet: "Message sent!",
    gesendetText: "I'll get back to you as soon as possible.",
    nochmal: "Send another message",
    name: "Name *", namePlatz: "John Smith",
    betrieb: "Business", betriebPlatz: "The Golden Lion",
    emailFeld: "Email *", emailPlatz: "john@example.com",
    anliegen: "Your request *", anliegenPlatz: "A short description of your project...",
    fehler: "Something went wrong. Please try again.",
    senden: "Send message", sendet: "Sending...",
    zustimmung1: "By sending you agree to the processing of your details according to the ",
    datenschutz: "privacy policy",
    zustimmung2: ". I reply within 24 hours.",
  },
  fuss: {
    text: "Websites for local businesses and small companies.",
    impressum: "Legal notice", datenschutz: "Privacy",
    rechte: "All rights reserved.",
  },
};

const ES: Texte = {
  nav: { leistungen: "Servicios", ueberMich: "Sobre mí", projekte: "Proyectos", kontakt: "Contacto", anfragen: "Solicitar proyecto" },
  leistungen: {
    titel: "Servicios",
    eintraege: [
      {
        eyebrow: "Smart Websites",
        titel: "Una web que trabaja por usted.",
        text: "Rápida, móvil, hecha para Google – con consultas, citas y reservas directamente en la página.",
        punkte: ["Consultas y citas", "Reserva en línea", "Carga en menos de un segundo"],
        alt: ["Página de inicio de la demo del concesionario", "La misma página en el móvil"],
      },
      {
        eyebrow: "Área de administración",
        titel: "Todo en un solo lugar.",
        text: "Consultas, reservas, inventario, visitas – usted mismo hace los cambios, sin agencia.",
        punkte: ["Consultas y citas", "Calendario de reservas e inventario", "Número de visitas"],
        alt: ["Vista general del área de administración de la demo", "Calendario de reservas de coches de alquiler"],
      },
      {
        eyebrow: "La IA como acelerador",
        titel: "Buena idea hoy. En línea mañana.",
        text: "La IA no sustituye una idea – hace que la ejecución sea rápida. Ejemplo Instagram: elegir foto, la IA escribe el texto, programar la publicación. Listo.",
        punkte: ["Publicaciones de Instagram en minutos", "Cambios en la web en días", "Textos e imágenes con su tono"],
        alt: ["Crear una publicación de Instagram en el área de administración", ""],
      },
    ],
  },
  geo: {
    eyebrow: "GEO – Generative Engine Optimization",
    titel: "Recomendado también por ChatGPT y Google AI.",
    text: "Hoy los clientes preguntan a una IA. Se menciona a quien ofrece datos claros – para eso preparo su web y su perfil de Google.",
    punkte: ["Datos estructurados", "Preguntas y respuestas", "Perfil de empresa de Google"],
    kopf: "Respuesta de la IA",
    frage: "¿Qué taller de Würzburg cambia neumáticos los sábados?",
    antwortName: "Autohaus Mustermann",
    antwort: " en Würzburg cambia neumáticos los sábados de 9 a 13 h y las citas se pueden reservar en línea. Los clientes valoran el negocio con 4,8 de 5 estrellas.",
    quellen: ["autohaus-mustermann.de", "Perfil de empresa de Google", "Reseñas · 4,8 ★"],
    aria: "Ejemplo: una respuesta de IA que recomienda el negocio",
  },
  ueber: {
    eyebrow: "Sobre mí",
    titel1: "Su persona de contacto",
    titel2: "en Würzburg",
    text: "Soy Ihsan, informático de gestión de Würzburg. Creo páginas web para negocios locales – con funciones que antes solo tenían las grandes empresas.",
    linkedin: "Conectar en LinkedIn",
    linkedinAria: "Perfil de LinkedIn de Ihsan Yilmaz",
    werte: ["Sin contratos de larga duración", "Cambios y actualizaciones sin complicaciones"],
    vorteile: [
      { titel: "Personal y sencillo", text: "Una persona de contacto, sin esperas." },
      { titel: "Ejecución rápida", text: "Normalmente pocas semanas hasta estar en línea." },
      { titel: "Precios justos", text: "Precio fijo por adelantado, sin costes ocultos." },
    ],
  },
  instagram: { unter: "Páginas web para negocios locales", folgen: "Seguir a @aiy.web", ansehen: "Ver publicación en Instagram" },
  projekte: {
    titel: "Proyectos",
    anfragen: "Solicitar su proyecto",
    status: { online: "En línea", inArbeit: "En curso" },
    tags: { web: "Desarrollo web", automatisierung: "Automatización" },
    eintraege: [
      { titel: "Web de concesionario", text: "Vehículos, consultas y citas de taller en una sola página.", tech: ["Next.js", "Cloudflare Pages", "Formulario de contacto", "Integración de tienda"] },
      { titel: "Web de restaurante", text: "Carta, horarios y contacto — con una estructura clara.", tech: ["Next.js", "Tailwind CSS", "Cloudflare Pages", "Carta inteligente"] },
      { titel: "Automatización de Instagram", text: "Crear publicaciones en el navegador, programarlas — y a la hora elegida todo sale solo.", tech: ["Cloudflare Worker", "API de Instagram", "Edición de imágenes", "Programación"] },
      { titel: "Reserva de coches de alquiler", text: "Elegir vehículo, fijar fechas, solicitar — disponibilidad en tiempo real.", tech: ["Next.js", "Calendario de reservas", "Disponibilidad", "Solicitud en línea"] },
    ],
  },
  kontakt: {
    eyebrow: "Contacto",
    titel1: "Trabajemos",
    titel2: "juntos",
    text: "Cuénteme de qué se trata — le respondo en un plazo de 24 horas.",
    email: "Correo electrónico",
    karte: "Ubicación – Oberer Mainkai 9, 97070 Würzburg (OpenStreetMap)",
    maps: "Abrir en Google Maps",
    gesendet: "¡Mensaje enviado!",
    gesendetText: "Le responderé lo antes posible.",
    nochmal: "Enviar otro mensaje",
    name: "Nombre *", namePlatz: "Juan Pérez",
    betrieb: "Negocio / local", betriebPlatz: "El León Dorado",
    emailFeld: "Correo electrónico *", emailPlatz: "juan@ejemplo.es",
    anliegen: "Su consulta *", anliegenPlatz: "Breve descripción de su proyecto...",
    fehler: "Algo ha salido mal. Inténtelo de nuevo.",
    senden: "Enviar mensaje", sendet: "Enviando...",
    zustimmung1: "Al enviar, acepta el tratamiento de sus datos según la ",
    datenschutz: "política de privacidad",
    zustimmung2: ". Respondo en un plazo de 24 horas.",
  },
  fuss: {
    text: "Páginas web para negocios locales y pequeñas empresas.",
    impressum: "Aviso legal", datenschutz: "Privacidad",
    rechte: "Todos los derechos reservados.",
  },
};

export const TEXTE: Record<Sprache, Texte> = { de: DE, en: EN, es: ES };
export const SPRACHEN: { kennung: Sprache; kurz: string; name: string }[] = [
  { kennung: "de", kurz: "DE", name: "Deutsch" },
  { kennung: "en", kurz: "EN", name: "English" },
  { kennung: "es", kurz: "ES", name: "Español" },
];
