// Alle Texte der Website in drei Sprachen. Deutsch ist die Vorlage – die
// Typen leiten sich daraus ab, damit in EN und ES kein Schluessel fehlt.
// Impressum und Datenschutz bleiben deutsch (Rechtstexte).

export type Sprache = "de" | "en" | "es";

const DE = {
  nav: { leistungen: "Leistungen", ueberMich: "Über mich", projekte: "Projekte", kontakt: "Kontakt", anfragen: "Projekt anfragen" },
  hero: {
    eyebrow: "Websites für lokale Betriebe",
    unter: "Es beginnt mit Ihrer Website – schnell gebaut, von Google und KI verstanden.",
    knopf: "Leistungen ansehen",
  },
  leistungen: {
    titel: "Leistungen",
    eintraege: [
      {
        eyebrow: "Smart Websites",
        titel: "Eine Website, die arbeitet.",
        text: "Schnell, mobil, für Google gebaut – Speisekarte, Reservierung, Anfragen und Buchungen direkt auf der Seite.",
        punkte: ["Reservierung & Anfragen", "Speisekarte & Online-Buchung", "Lädt in unter einer Sekunde"],
        ansichten: ["Autohaus", "Café", "Speisekarte", "Reservierung", "Mietwagen", "Finanzierung"],
      },
      {
        eyebrow: "Verwaltungsbereich",
        titel: "Alles an einer Stelle.",
        text: "Reservierungen, Speisekarte, Belegung, Besucherzahlen – Sie ändern selbst, ohne Agentur.",
        punkte: ["Anfragen & Reservierungen", "Speisekarte & Belegungsplan", "Besucherzahlen"],
        ansichten: ["Übersicht", "Speisekarte", "Belegung", "Monitoring"],
      },
      {
        eyebrow: "KI als Beschleuniger",
        titel: "Gute Idee heute. Online morgen.",
        text: "KI ersetzt keine Idee – sie macht die Umsetzung schnell. Der Koch schickt die Wochenkarte per Messenger, kurz darauf steht sie online. Instagram: Foto wählen, der Text kommt von der KI.",
        punkte: ["Speisekarte per Messenger in Minuten", "Instagram-Beiträge in Minuten", "Änderungen an der Website in Tagen"],
        ansichten: ["Karte per Messenger", "Content erstellen", "Website ändern"],
      },
    ],
  },
  geo: {
    eyebrow: "GEO – Generative Engine Optimization",
    titel: "Auch von ChatGPT & Google AI empfohlen.",
    text: "Kunden fragen heute eine KI. Genannt wird, wer klare Fakten liefert – dafür richte ich Website und Google-Profil ein.",
    punkte: ["Strukturierte Daten", "Fragen & Antworten", "Google-Unternehmensprofil"],
    kopf: "KI-Antwort",
    beispiele: [
      {
        frage: "Welche Werkstatt in Würzburg macht samstags Reifenwechsel?",
        name: "Autohaus Mustermann",
        antwort: " in Würzburg bietet samstags von 9 bis 13 Uhr Reifenwechsel an, Termine lassen sich online buchen.",
        quellen: ["autohaus-mustermann.de", "Google Unternehmensprofil", "Bewertungen · 4,8 ★"],
      },
      {
        frage: "Wo kann ich in Würzburg sonntags gemütlich frühstücken?",
        name: "Café Mustermann",
        antwort: " in der Innenstadt serviert sonntags bis 14 Uhr Frühstück, Tische lassen sich online reservieren.",
        quellen: ["cafe-mustermann.de", "Speisekarte", "Bewertungen · 4,7 ★"],
      },
      {
        frage: "Wo miete ich in Würzburg kurzfristig einen Transporter?",
        name: "Autohaus Mustermann",
        antwort: " vermietet Transporter ab 59 € am Tag. Freie Tage sind online sichtbar und direkt buchbar.",
        quellen: ["autohaus-mustermann.de/mietwagen", "Belegungsplan", "Bewertungen · 4,8 ★"],
      },
    ],
    aria: "Beispiel: KI-Antwort, die den Betrieb empfiehlt",
  },
  ueber: {
    eyebrow: "Über mich",
    titel1: "Ihr Ansprechpartner",
    titel2: "aus Würzburg",
    text: "Ich bin Ihsan, Wirtschaftsinformatiker aus Würzburg. Ich baue Websites für lokale Betriebe – mit Funktionen, die früher nur große Firmen hatten.",
    linkedin: "Auf LinkedIn vernetzen",
    linkedinAria: "LinkedIn-Profil von Ihsan Yilmaz",
    werte: ["Keine langen Vertragslaufzeiten", "Änderungen und Updates unkompliziert möglich"],
    vorteile: [
      { titel: "Persönlich & unkompliziert", text: "Eine Ansprechperson, keine Warteschleife." },
      { titel: "Schnelle Umsetzung", text: "In der Regel wenige Wochen bis online." },
      { titel: "Faire Preise", text: "Festpreis vorab, keine versteckten Kosten." },
    ],
  },
  instagram: { unter: "Websites für lokale Betriebe", folgen: "@aiy.web folgen", ansehen: "Beitrag auf Instagram ansehen" },
  projekte: {
    titel: "Projekte",
    anfragen: "Ihr Projekt anfragen",
    status: { online: "Online", inArbeit: "In Arbeit" },
    tags: { web: "Webentwicklung", automatisierung: "Automatisierung" },
    eintraege: [
      { titel: "Autohaus-Website", text: "Fahrzeuge, Anfragen und Werkstatt-Termine auf einer Seite.", tech: ["Next.js", "Cloudflare Pages", "Kontaktformular", "Webshop-Anbindung"] },
      { titel: "Café-Website", text: "Speisekarte, die der Koch per WhatsApp aktualisiert – Wochenkarte ohne Umweg über die Agentur.", tech: ["Cloudflare Pages", "WhatsApp-Update", "Speisekarte", "Blog"] },
      { titel: "Planungsbüro-Website", text: "Zweisprachige Seite für ein Architektur- und Planungsbüro – Projekte, Leistungen, internationale Referenzen.", tech: ["Deutsch / Türkisch", "Diashow", "SEO & schema.org"] },
      { titel: "Instagram-Automatisierung", text: "Beiträge im Browser bauen, einplanen — und zur gewählten Zeit geht alles von selbst raus.", tech: ["Cloudflare Worker", "Instagram-API", "Bildbearbeitung", "Zeitplanung"] },
      { titel: "Mietwagen-Buchungstool", text: "Fahrzeug wählen, Zeitraum festlegen, anfragen — Verfügbarkeit live.", tech: ["Next.js", "Buchungskalender", "Verfügbarkeiten", "Online-Anfrage"] },
    ],
  },
  kontakt: {
    eyebrow: "Kontakt",
    titel1: "Lassen Sie uns",
    titel2: "zusammenarbeiten",
    text: "Schreiben Sie mir, worum es geht — ich melde mich innerhalb von 24 Stunden.",
    email: "E-Mail",
    karte: "Standort – Oberer Mainkai 9, 97070 Würzburg (OpenStreetMap)",
    maps: "In Google Maps öffnen",
    gesendet: "Nachricht gesendet!",
    gesendetText: "Ich melde mich so schnell wie möglich bei Ihnen.",
    nochmal: "Weitere Nachricht senden",
    name: "Name *", namePlatz: "Max Mustermann",
    betrieb: "Betrieb / Lokal", betriebPlatz: "Zum goldenen Löwen",
    emailFeld: "E-Mail *", emailPlatz: "max@muster.de",
    anliegen: "Ihr Anliegen *", anliegenPlatz: "Kurze Beschreibung Ihres Projekts...",
    fehler: "Etwas ist schiefgelaufen. Bitte versuchen Sie es erneut.",
    senden: "Nachricht senden", sendet: "Wird gesendet...",
    zustimmung1: "Mit dem Absenden stimmen Sie der Verarbeitung Ihrer Angaben gemäß ",
    datenschutz: "Datenschutzerklärung",
    zustimmung2: " zu. Ich antworte innerhalb von 24 Stunden.",
  },
  fuss: {
    text: "Websites für lokale Betriebe und kleine Unternehmen.",
    impressum: "Impressum", datenschutz: "Datenschutz",
    rechte: "Alle Rechte vorbehalten.",
  },
};

export type Texte = typeof DE;

const EN: Texte = {
  nav: { leistungen: "Services", ueberMich: "About", projekte: "Projects", kontakt: "Contact", anfragen: "Request a project" },
  hero: {
    eyebrow: "Websites for local businesses",
    unter: "It starts with your website – built fast, understood by Google and AI.",
    knopf: "See services",
  },
  leistungen: {
    titel: "Services",
    eintraege: [
      {
        eyebrow: "Smart Websites",
        titel: "A website that works for you.",
        text: "Fast, mobile, built for Google – menu, reservations, enquiries and bookings right on the page.",
        punkte: ["Reservations & enquiries", "Menu & online booking", "Loads in under a second"],
        ansichten: ["Car dealer", "Café", "Menu", "Reservation", "Car rental", "Financing"],
      },
      {
        eyebrow: "Admin area",
        titel: "Everything in one place.",
        text: "Reservations, menu, bookings, visitor numbers – you make changes yourself, no agency needed.",
        punkte: ["Enquiries & reservations", "Menu & booking calendar", "Visitor numbers"],
        ansichten: ["Overview", "Menu", "Bookings", "Analytics"],
      },
      {
        eyebrow: "AI as an accelerator",
        titel: "Good idea today. Online tomorrow.",
        text: "AI doesn't replace an idea – it makes execution fast. The chef sends the weekly menu via messenger, minutes later it is online. Instagram: pick a photo, the AI writes the text.",
        punkte: ["Menu via messenger in minutes", "Instagram posts in minutes", "Website changes in days"],
        ansichten: ["Menu via messenger", "Create content", "Edit website"],
      },
    ],
  },
  geo: {
    eyebrow: "GEO – Generative Engine Optimization",
    titel: "Recommended by ChatGPT & Google AI, too.",
    text: "Customers ask an AI these days. It names whoever provides clear facts – that's what I set up your website and Google profile for.",
    punkte: ["Structured data", "Questions & answers", "Google Business Profile"],
    kopf: "AI answer",
    beispiele: [
      {
        frage: "Which garage in Würzburg changes tyres on Saturdays?",
        name: "Autohaus Mustermann",
        antwort: " in Würzburg changes tyres on Saturdays from 9 am to 1 pm, and appointments can be booked online.",
        quellen: ["autohaus-mustermann.de", "Google Business Profile", "Reviews · 4.8 ★"],
      },
      {
        frage: "Where can I have a relaxed Sunday breakfast in Würzburg?",
        name: "Café Mustermann",
        antwort: " in the city centre serves breakfast on Sundays until 2 pm, and tables can be reserved online.",
        quellen: ["cafe-mustermann.de", "Menu", "Reviews · 4.7 ★"],
      },
      {
        frage: "Where can I rent a van at short notice in Würzburg?",
        name: "Autohaus Mustermann",
        antwort: " rents out vans from €59 a day. Free days are shown online and can be booked directly.",
        quellen: ["autohaus-mustermann.de/mietwagen", "Booking calendar", "Reviews · 4.8 ★"],
      },
    ],
    aria: "Example: an AI answer recommending the business",
  },
  ueber: {
    eyebrow: "About me",
    titel1: "Your contact",
    titel2: "in Würzburg",
    text: "I'm Ihsan, a business IT specialist from Würzburg. I build websites for local businesses – with features that used to be reserved for big companies.",
    linkedin: "Connect on LinkedIn",
    linkedinAria: "LinkedIn profile of Ihsan Yilmaz",
    werte: ["No long contract terms", "Changes and updates made easy"],
    vorteile: [
      { titel: "Personal & straightforward", text: "One contact person, no hotline." },
      { titel: "Fast delivery", text: "Usually a few weeks until you're online." },
      { titel: "Fair prices", text: "Fixed price up front, no hidden costs." },
    ],
  },
  instagram: { unter: "Websites for local businesses", folgen: "Follow @aiy.web", ansehen: "View post on Instagram" },
  projekte: {
    titel: "Projects",
    anfragen: "Request your project",
    status: { online: "Live", inArbeit: "In progress" },
    tags: { web: "Web development", automatisierung: "Automation" },
    eintraege: [
      { titel: "Car dealer website", text: "Vehicles, enquiries and workshop appointments on one site.", tech: ["Next.js", "Cloudflare Pages", "Contact form", "Shop integration"] },
      { titel: "Café website", text: "A menu the chef updates via WhatsApp – weekly specials without going through an agency.", tech: ["Cloudflare Pages", "WhatsApp update", "Menu", "Blog"] },
      { titel: "Planning office website", text: "Bilingual site for an architecture and planning office – projects, services, international references.", tech: ["German / Turkish", "Slideshow", "SEO & schema.org"] },
      { titel: "Instagram automation", text: "Build posts in the browser, schedule them — and at the chosen time everything goes out by itself.", tech: ["Cloudflare Worker", "Instagram API", "Image editing", "Scheduling"] },
      { titel: "Rental car booking tool", text: "Choose a vehicle, set the dates, send a request — availability live.", tech: ["Next.js", "Booking calendar", "Availability", "Online request"] },
    ],
  },
  kontakt: {
    eyebrow: "Contact",
    titel1: "Let's work",
    titel2: "together",
    text: "Tell me what it's about — I'll get back to you within 24 hours.",
    email: "Email",
    karte: "Location – Oberer Mainkai 9, 97070 Würzburg (OpenStreetMap)",
    maps: "Open in Google Maps",
    gesendet: "Message sent!",
    gesendetText: "I'll get back to you as soon as possible.",
    nochmal: "Send another message",
    name: "Name *", namePlatz: "John Smith",
    betrieb: "Business", betriebPlatz: "The Golden Lion",
    emailFeld: "Email *", emailPlatz: "john@example.com",
    anliegen: "Your request *", anliegenPlatz: "A short description of your project...",
    fehler: "Something went wrong. Please try again.",
    senden: "Send message", sendet: "Sending...",
    zustimmung1: "By sending you agree to the processing of your details according to the ",
    datenschutz: "privacy policy",
    zustimmung2: ". I reply within 24 hours.",
  },
  fuss: {
    text: "Websites for local businesses and small companies.",
    impressum: "Legal notice", datenschutz: "Privacy",
    rechte: "All rights reserved.",
  },
};

const ES: Texte = {
  nav: { leistungen: "Servicios", ueberMich: "Sobre mí", projekte: "Proyectos", kontakt: "Contacto", anfragen: "Solicitar proyecto" },
  hero: {
    eyebrow: "Páginas web para negocios locales",
    unter: "Todo empieza con su página web – creada rápido, entendida por Google y la IA.",
    knopf: "Ver servicios",
  },
  leistungen: {
    titel: "Servicios",
    eintraege: [
      {
        eyebrow: "Smart Websites",
        titel: "Una web que trabaja por usted.",
        text: "Rápida, móvil, hecha para Google – carta, reservas, consultas y citas directamente en la página.",
        punkte: ["Reservas y consultas", "Carta y reserva en línea", "Carga en menos de un segundo"],
        ansichten: ["Concesionario", "Café", "Carta", "Reserva", "Alquiler", "Financiación"],
      },
      {
        eyebrow: "Área de administración",
        titel: "Todo en un solo lugar.",
        text: "Reservas, carta, ocupación, visitas – usted mismo hace los cambios, sin agencia.",
        punkte: ["Consultas y reservas", "Carta y calendario de reservas", "Número de visitas"],
        ansichten: ["Resumen", "Carta", "Reservas", "Estadísticas"],
      },
      {
        eyebrow: "La IA como acelerador",
        titel: "Buena idea hoy. En línea mañana.",
        text: "La IA no sustituye una idea – hace que la ejecución sea rápida. El cocinero envía la carta semanal por mensajería y poco después está en línea. Instagram: elegir foto, la IA escribe el texto.",
        punkte: ["Carta por mensajería en minutos", "Publicaciones de Instagram en minutos", "Cambios en la web en días"],
        ansichten: ["Carta por mensajería", "Crear contenido", "Editar web"],
      },
    ],
  },
  geo: {
    eyebrow: "GEO – Generative Engine Optimization",
    titel: "Recomendado también por ChatGPT y Google AI.",
    text: "Hoy los clientes preguntan a una IA. Se menciona a quien ofrece datos claros – para eso preparo su web y su perfil de Google.",
    punkte: ["Datos estructurados", "Preguntas y respuestas", "Perfil de empresa de Google"],
    kopf: "Respuesta de la IA",
    beispiele: [
      {
        frage: "¿Qué taller de Würzburg cambia neumáticos los sábados?",
        name: "Autohaus Mustermann",
        antwort: " en Würzburg cambia neumáticos los sábados de 9 a 13 h y las citas se reservan en línea.",
        quellen: ["autohaus-mustermann.de", "Perfil de empresa de Google", "Reseñas · 4,8 ★"],
      },
      {
        frage: "¿Dónde puedo desayunar tranquilo un domingo en Würzburg?",
        name: "Café Mustermann",
        antwort: " en el centro sirve desayunos los domingos hasta las 14 h y las mesas se reservan en línea.",
        quellen: ["cafe-mustermann.de", "Carta", "Reseñas · 4,7 ★"],
      },
      {
        frage: "¿Dónde alquilo una furgoneta con poca antelación en Würzburg?",
        name: "Autohaus Mustermann",
        antwort: " alquila furgonetas desde 59 € al día. Los días libres se ven en línea y se reservan directamente.",
        quellen: ["autohaus-mustermann.de/mietwagen", "Calendario de reservas", "Reseñas · 4,8 ★"],
      },
    ],
    aria: "Ejemplo: una respuesta de IA que recomienda el negocio",
  },
  ueber: {
    eyebrow: "Sobre mí",
    titel1: "Su persona de contacto",
    titel2: "en Würzburg",
    text: "Soy Ihsan, informático de gestión de Würzburg. Creo páginas web para negocios locales – con funciones que antes solo tenían las grandes empresas.",
    linkedin: "Conectar en LinkedIn",
    linkedinAria: "Perfil de LinkedIn de Ihsan Yilmaz",
    werte: ["Sin contratos de larga duración", "Cambios y actualizaciones sin complicaciones"],
    vorteile: [
      { titel: "Personal y sencillo", text: "Una persona de contacto, sin esperas." },
      { titel: "Ejecución rápida", text: "Normalmente pocas semanas hasta estar en línea." },
      { titel: "Precios justos", text: "Precio fijo por adelantado, sin costes ocultos." },
    ],
  },
  instagram: { unter: "Páginas web para negocios locales", folgen: "Seguir a @aiy.web", ansehen: "Ver publicación en Instagram" },
  projekte: {
    titel: "Proyectos",
    anfragen: "Solicitar su proyecto",
    status: { online: "En línea", inArbeit: "En curso" },
    tags: { web: "Desarrollo web", automatisierung: "Automatización" },
    eintraege: [
      { titel: "Web de concesionario", text: "Vehículos, consultas y citas de taller en una sola página.", tech: ["Next.js", "Cloudflare Pages", "Formulario de contacto", "Integración de tienda"] },
      { titel: "Web de cafetería", text: "Una carta que el cocinero actualiza por WhatsApp – menú semanal sin pasar por la agencia.", tech: ["Cloudflare Pages", "Actualización por WhatsApp", "Carta", "Blog"] },
      { titel: "Web de estudio de planificación", text: "Web bilingüe para un estudio de arquitectura y planificación – proyectos, servicios, referencias internacionales.", tech: ["Alemán / Turco", "Presentación", "SEO y schema.org"] },
      { titel: "Automatización de Instagram", text: "Crear publicaciones en el navegador, programarlas — y a la hora elegida todo sale solo.", tech: ["Cloudflare Worker", "API de Instagram", "Edición de imágenes", "Programación"] },
      { titel: "Reserva de coches de alquiler", text: "Elegir vehículo, fijar fechas, solicitar — disponibilidad en tiempo real.", tech: ["Next.js", "Calendario de reservas", "Disponibilidad", "Solicitud en línea"] },
    ],
  },
  kontakt: {
    eyebrow: "Contacto",
    titel1: "Trabajemos",
    titel2: "juntos",
    text: "Cuénteme de qué se trata — le respondo en un plazo de 24 horas.",
    email: "Correo electrónico",
    karte: "Ubicación – Oberer Mainkai 9, 97070 Würzburg (OpenStreetMap)",
    maps: "Abrir en Google Maps",
    gesendet: "¡Mensaje enviado!",
    gesendetText: "Le responderé lo antes posible.",
    nochmal: "Enviar otro mensaje",
    name: "Nombre *", namePlatz: "Juan Pérez",
    betrieb: "Negocio / local", betriebPlatz: "El León Dorado",
    emailFeld: "Correo electrónico *", emailPlatz: "juan@ejemplo.es",
    anliegen: "Su consulta *", anliegenPlatz: "Breve descripción de su proyecto...",
    fehler: "Algo ha salido mal. Inténtelo de nuevo.",
    senden: "Enviar mensaje", sendet: "Enviando...",
    zustimmung1: "Al enviar, acepta el tratamiento de sus datos según la ",
    datenschutz: "política de privacidad",
    zustimmung2: ". Respondo en un plazo de 24 horas.",
  },
  fuss: {
    text: "Páginas web para negocios locales y pequeñas empresas.",
    impressum: "Aviso legal", datenschutz: "Privacidad",
    rechte: "Todos los derechos reservados.",
  },
};

export const TEXTE: Record<Sprache, Texte> = { de: DE, en: EN, es: ES };
export const SPRACHEN: { kennung: Sprache; kurz: string; name: string }[] = [
  { kennung: "de", kurz: "DE", name: "Deutsch" },
  { kennung: "en", kurz: "EN", name: "English" },
  { kennung: "es", kurz: "ES", name: "Español" },
];
